#
# production configuration
#
spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.69:3307/webdb?characterEncoding=utf8
      username: webdb
      password: '{cipher}AQCUnGr6/+DXnqcq8oqk/jnr1Glg2oHnfGnRbGXNQI8zDpU7FG9ZbDQxsSv2OFcBH72Yy/PlpsHh+7F7kyJ13iQfV4SZzT7ZpCZ2uVRH8NoajOf67GptwS8EvVJdwt2OkRo2s573ESVmr4tYK7nhP5PA3G3iLp16C0Th+HwZf+tgUixewB+D0IdmoslsEcg6vviOMSgc1RxpaqZ6nX7KNOQKwK74nHDpQO82h2h0wrQ+7ngVDWehwfp7TT/mAml66O0Vms81RssLhtA3td3+GSY2IfJmNYdSw9a7IUdW6fX8Z5ziibwlcaMBCzWgEW6PN6LCbua1WX332LEB5C7FwdRLp58uvnj8zeF+koa7yAy0Z9Ww3vEnpQPLSpK4F4qa3Ug='
mybatis:
   config-location: classpath:mybatis/configuration.xml
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.69:8761/eureka
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            msa:
               service:
                  gallery:
                     exception: ERROR