#
# production configuration
#
spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.69:3307/webdb?characterEncoding=utf8
      username: webdb
      password: '{cipher}AQCyNNTy02jfZOZhvYXjJYKfuMSo8TV5aaHT/s7kefMF5QDG0aYwjjnG4sPVKLrbIdeKJzbcDGZLRYUEh3YqDVCSK+liNZlCJlb0giGux5446w2vlhiP9cLTiKVZx0b61mnhVcVGxtVuv42gLwMjRp8oYtLoBB/3/eIxsO9HAaw3li5tACiMXog3Qwv0KBG6WaSPXlQAkI8fvgv9QIDyu24uWIPMbOkHvwy38yB211ez4XSaBxmb4Ku7Qjcrw4390vvXNeDxHvStXaQjDqn/apx57ygTSGr1+U+ihyaIqrl2rj++7mrVc0qwLB2IbyTY/BVoLvbHfZNHPt50UJQ2DptdJqVMY1D3pQVNTJVQ8OWW079/DEtFd6hyJlQWKzNNzGs='
mybatis:
   config-location: classpath:mybatis/configuration.xml
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.69:8761/eureka
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            msa:
               service:
                  guestbook:
                     exception: ERROR